version: '3.4'

services:

  prometheus:
    image: ${DOCKER_REGISTRY-}prometheus
    restart: always
    build:
      context: Infrastructure/Prometheus
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    # These commands need if only need to change log level. By default it's not needed
    # command:
    #   - "--config.file=/etc/prometheus/prometheus.yml"
    #   - "--log.level=debug"

  # Setup Grafana once, don't rebuild it to keep dashboards
  # grafana:
  #   image: grafana/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=12345 #grafana dashboard u: admin p: 12345
  #   restart: always
  #   ports:
  #     - 3000:3000

  # Just simple Ubuntu image with installed Curl and Telnet if some diagnostics needed
  ubuntu:
    image: ${DOCKER_REGISTRY-}ubuntu
    restart: always
    command: sleep infinity
    build:
      context: Infrastructure/Ubuntu
      dockerfile: Dockerfile
