version: '3.4'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.9.0}
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 12

    command: sh -c './bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu && exec /usr/local/bin/docker-entrypoint.sh'
    ports:
      - 9200:9200
    environment:
      - cluster.name=dev
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    volumes:
      - /usr/share/elasticsearch/data
      - ./data/config/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4GB

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.10.1
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - 8200:8200
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    depends_on:
      - elasticsearch

  webapi1:
    environment:
      - ElasticApm__ServerUrl=http://apm-server:8200
      - ElasticApm__Enabled=true
      - ElasticApm__CentralConfig=false
    depends_on:
      - apm-server
